language: python
sudo: false # build in a container, which is a lot faster! http://docs.travis-ci.com/user/migrating-from-legacy/
cache: pip
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
    - 3.7
    - 3.8
    - 3.9
    - 3.10
    # - pypy # problem with Travis in 2020, with building openssl for some reason even though it's not used
    - pypy3

install:
    - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install importlib unittest2; fi
    - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then pip install --install-option='--no-cython-compile' cython ; fi
    - pip install 'coverage<4'
    - pip install coveralls

script:
    - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then python setup.py build_ext --inplace ; fi
    - nosetests -vv --with-coverage

after_success:
    coveralls

notifications:
    email:
        on_success: change
        on_failure: change

# PyPy can fail because of Cython - but this should not happen anymore since the related unit tests are now directly skipped if running under PyPy
#matrix:
#    allow_failures:
#        - python: pypy
#        - python: pypy3
